services:
  gateway:
    build:
      context: .
      dockerfile: Gateway/Dockerfile
    ports:
      - "8000:8080"
    depends_on:
      - users.api
      - settings.api
      - signalr.srv
      - rabbit
  settings.api:
    build:
      context: .
      dockerfile: SettingsService/Dockerfile
    depends_on:
      - signalr.srv
      - rabbit
    volumes:
      - ./settings:/app/settings
  users.api:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    depends_on:
      - signalr.srv
      - rabbit
    volumes:
      - ./users:/app/users
  signalr.srv:
    build:
      context: .
      dockerfile: SignalRService/Dockerfile
  rabbit:
    image: rabbitmq:3-alpine
